"use client";
import { useState,useEffect,useRef } from "react";

export default function MyGeaNativeV5(){
 const [id,setId]=useState("1");
 const [lang,setLang]=useState("en");
 const [holo,setHolo]=useState(false);
 const [live,setLive]=useState(false);
 const [liveVideo,setLiveVideo]=useState(false);
 const [isPlaying,setIsPlaying]=useState(true);
 const [zoom,setZoom]=useState(1);
 const [fit,setFit]=useState("cover");
 const [phoneFit,setPhoneFit]=useState(false);
 const [facing,setFacing]=useState("user");
 const [activePanel,setActivePanel]=useState(null);
 const [transText,setTransText]=useState("Tap mic speak English");
 const [chatId,setChatId]=useState(null);
 const [shareId,setShareId]=useState(null);
 const [theme,setTheme]=useState("HOLO Dark");
 const [backupLog,setBackupLog]=useState("API JSON + Phone Fit Connected");
 const [adPlaying,setAdPlaying]=useState(true);
 const videoRef=useRef(null);
 const canvasRef=useRef(null);
 const fileInputRef=useRef(null);
 const videoInputRef=useRef(null);
 const backupProfilesJSON={
  version:"V5.1 Phone Fit Global Standard",
  ceo:"Apostle Dr Oladele Mighty Hassan",
  rc:"9882150",
  company:"Geapple Inc",
  ecosystem:"www.geapple.com",
  security:"gsiacyber.com GSIA Secured",
  apis:["camera_api","video_api","holo_api","share_link_api","geatune_api","geapay_api","legal_ndpa_api","phone_fit_api","fullscreen_api"],
  google:"https://www.google.com/search?q=Geapple+Ecosystem",
  legal:{terms:"/legal",ndpa:"/ndpa"},
  files:{json:"backupProfiles.json",js:"geappleApi.js",jsx:"MyGeaNative.jsx"}
 };
 const [posts,setPosts]=useState([
  {id:1,u:"Apostle Dr Mighty",t:"MYGEA V5.1 Phone Fit 📱 + Upload + GeaTune + GeaPay LIVE! 🌍",l:152,liked:false,comments:["Weldone!"],shares:12},
  {id:2,u:"GEAPPLE CEO",t:"Tap Screen = Fit Phone 📱 • Double Tap = Full Screen ⛶",l:98,liked:false,comments:[],shares:5},
 ]);
 useEffect(()=>{ const p=window.location.pathname.split('/').pop(); if(p &&!isNaN(p)) setId(p); },[]);

 const startCamera=async()=>{ try{ const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:1280},audio:true}); if(videoRef.current){videoRef.current.srcObject=s; videoRef.current.play(); setLive(true); setLiveVideo(false); setIsPlaying(true);} doBackup('camera_api','5G ON'); }catch{alert("Allow Camera!");} };
 const startVideoStream=async()=>{ try{ const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment",width:1920},audio:true}); if(videoRef.current){videoRef.current.srcObject=s; videoRef.current.play(); setLive(true); setLiveVideo(true); setIsPlaying(true);} doBackup('video_api','LIVE ON'); }catch{alert("Allow Camera!");} };
 const stopAll=()=>{ if(videoRef.current?.srcObject){videoRef.current.srcObject.getTracks().forEach(t=>t.stop());} setLive(false); setLiveVideo(false); };
 const togglePlay=()=>{ if(videoRef.current){ if(isPlaying) videoRef.current.pause(); else videoRef.current.play(); setIsPlaying(!isPlaying);} };
 const flipSelfie=()=>{ setFacing(f=>f==="user"?"environment":"user"); setTimeout(()=>{if(live) startCamera();},400); };
 const togglePhoneFit=()=>{ setPhoneFit(!phoneFit); if(!phoneFit){setFit("contain"); setZoom(1); doBackup('phone_fit_api','Phone Fit 📱 ON');} else{setFit("cover"); doBackup('phone_fit_api','Phone Fit OFF');} };
 const goFullScreen=()=>{ if(videoRef.current){ if(videoRef.current.requestFullscreen) videoRef.current.requestFullscreen(); else if(videoRef.current.webkitRequestFullscreen) videoRef.current.webkitRequestFullscreen(); doBackup('fullscreen_api','Full Screen 📱'); } };
 const snapshot=()=>{
  if(!videoRef.current ||!canvasRef.current) return;
  const c=canvasRef.current; c.width=videoRef.current.videoWidth; c.height=videoRef.current.videoHeight;
  const ctx=c.getContext('2d'); ctx.drawImage(videoRef.current,0,0);
  if(holo){ ctx.fillStyle='rgba(255,0,255,0.2)'; ctx.fillRect(0,0,c.width,c.height); }
  const url=c.toDataURL("image/png"); const a=document.createElement('a'); a.href=url; a.download=`MYGEA_HOLO_5G_${Date.now()}.png`; a.click();
  localStorage.setItem('geapple_backup_v5',JSON.stringify({...backupProfilesJSON,snapshot:url.slice(0,50),time:Date.now()}));
  setBackupLog("Holographic 5G Image + JSON Backup Saved");
 };
 const doBackup=(k,v)=>{ localStorage.setItem(`geapple_${k}`,v); localStorage.setItem('geapple_backup_v5',JSON.stringify({...backupProfilesJSON,last:k,lastVal:v,time:Date.now()})); setBackupLog(`API JSON: ${k}=${v} • ${new Date().toLocaleTimeString()}`); };
 const handleFileUpload=(e)=>{ const f=e.target.files[0]; if(f){ alert(`File: ${f.name} • Linked to Backup Menu • JSON!`); doBackup('file_upload_api',f.name); setPosts([{id:Date.now(),u:"You 📁",t:`Uploaded File: ${f.name} 📁`,l:0,liked:false,comments:[],shares:0},...posts]); } };
 const handleVideoUpload=(e)=>{ const f=e.target.files[0]; if(f){ alert(`Video: ${f.name} • Adverts Ready!`); doBackup('video_upload_api',f.name); setPosts([{id:Date.now(),u:"You 🎥",t:`Uploaded Video: ${f.name} 🎞️`,l:0,liked:false,comments:[],shares:0},...posts]); } };
 const like=(pid)=>{ setPosts(posts.map(p=>p.id===pid?{...p,l:p.liked?p.l-1:p.l+1,liked:!p.liked}:p)); };
 const shareLinkAction=(pid=null)=>{ const url=window.location.href+(pid?`?post=${pid}`:''); if(navigator.share){navigator.share({title:'MYGEA V5',text:'Join Geapple!',url}).catch(()=>{navigator.clipboard.writeText(url); alert('🖇️ Copied! '+url);});}else{navigator.clipboard.writeText(url); alert('🖇️ Link Copied! 🔗 '+url); setShareId(pid||'global');} doBackup('share_link_api',url); if(pid) setPosts(posts.map(p=>p.id===pid?{...p,shares:(p.shares||0)+1}:p)); };
 const shareTo=(pl,pid)=>{ const url=window.location.href+`?post=${pid}`; if(pl==='wa') window.open(`https://wa.me/?text=${encodeURIComponent('Join MYGEA V5! '+url)}`); if(pl==='fb') window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`); if(pl==='yt') window.open(`https://www.youtube.com/`); if(pl==='ig') window.open(`https://www.instagram.com/`); if(pl==='tt') window.open(`https://www.tiktok.com/`); if(pl==='google') window.open(`https://www.google.com/search?q=Geapple+Ecosystem+MYGEA`); if(pl==='copy'){navigator.clipboard.writeText(url); alert('🔗 Copied! '+url);} doBackup('share_'+pl,url); };
 const translateVoice=()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){alert("Use Chrome");return;} const rec=new SR(); rec.lang='en-US'; rec.onresult=(e)=>{ let txt=e.results[0][0].transcript; let tr=txt; if(lang==='yo') tr=`Yoruba: ${txt}`; if(lang==='ig') tr=`Igbo: ${txt}`; if(lang==='ha') tr=`Hausa: ${txt}`; if(lang==='pcm') tr=`Pidgin: ${txt}`; if(lang==='fr') tr=`French: ${txt}`; setTransText(tr); speechSynthesis.speak(new SpeechSynthesisUtterance(tr)); }; rec.start(); setTransText("Listening..."); };
 if(id!=="1") return <div style={{background:'#000',color:'#fff',minHeight:'100vh',padding:20,textAlign:'center'}}><h2 style={{color:'#0f0'}}>APP {id}</h2><button onClick={()=>location.href='/apps/1'} style={{background:'#0f0',color:'#000',padding:12,borderRadius:10}}>Go MYGEA V5</button></div>;
 return(
 <div style={{background:theme==="Ocean Blue"?'#001122':theme==="Neon Green"?'#001100':'#000',minHeight:'100vh',color:'#fff',display:'flex',fontFamily:'sans-serif'}}>
  <style>{`@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}.spin{animation:spin 4s linear infinite}`}</style>
  <canvas ref={canvasRef} style={{display:'none'}}/>
  <input type="file" ref={fileInputRef} onChange={handleFileUpload} style={{display:'none'}} accept=".pdf,.doc,.docx,.zip,.json,.js,.jsx"/>
  <input type="file" ref={videoInputRef} onChange={handleVideoUpload} style={{display:'none'}} accept="video/*"/>

  <div style={{width:64,background:'#0a0a0a',borderRight:'1px solid #0f03',display:'flex',flexDirection:'column',alignItems:'center',gap:7,padding:'10px 0',position:'fixed',height:'100vh',zIndex:30,overflowY:'auto'}}>
   <div style={{width:46,height:46,background:'#111',borderRadius:12,display:'flex',alignItems:'center',justifyContent:'center',border:'1px solid #0f0'}}><span className="spin" style={{fontSize:26}}>🌍</span></div>
   <button onClick={()=>setActivePanel(activePanel==='home'?null:'home')} style={{background:activePanel==='home'?'#0f0':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🏠</button>
   <button onClick={()=>{setActivePanel('camera'); if(!live) startCamera();}} style={{background:activePanel==='camera'?'#0f0':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>📷</button>
   <button onClick={()=>{startVideoStream(); setActivePanel('video');}} style={{background:liveVideo?'#f00':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>📹</button>
   <button onClick={()=>{setHolo(!holo); setActivePanel('holo');}} style={{background:holo?'#f0f':'#111',border:`1px solid ${holo?'#f0f':'#222'}`,width:42,height:42,borderRadius:12}}>👁️</button>
   <button onClick={()=>fileInputRef.current.click()} style={{background:'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>📁</button>
   <button onClick={()=>videoInputRef.current.click()} style={{background:'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🎥</button>
   <button onClick={()=>setActivePanel('reel')} style={{background:activePanel==='reel'?'#fa0':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🎞️</button>
   <button onClick={()=>setActivePanel('geatune')} style={{background:activePanel==='geatune'?'#1DB954':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🎵</button>
   <button onClick={()=>setActivePanel('geapay')} style={{background:activePanel==='geapay'?'#00D632':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>💳</button>
   <button onClick={()=>setActivePanel(activePanel==='theme'?null:'theme')} style={{background:activePanel==='theme'?'#fa0':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🎨</button>
   <button onClick={()=>setActivePanel(activePanel==='lang'?null:'lang')} style={{background:activePanel==='lang'?'#0ff':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>🌐</button>
   <button onClick={()=>shareLinkAction()} style={{background:'#0f0',border:'1px solid #0f0',width:42,height:42,borderRadius:12}}>🖇️</button>
   <button onClick={()=>setActivePanel('adverts')} style={{background:activePanel==='adverts'?'#f00':'#111',border:'1px solid #222',width:42,height:42,borderRadius:12}}>📺</button>
   <button onClick={()=>setActivePanel('legal')} style={{background:activePanel==='legal'?'#fff':'#111',color:activePanel==='legal'?'#000':'#fff',border:'1px solid #222',width:42,height:42,borderRadius:12}}>⚖️</button>
   <button onClick={()=>setActivePanel(activePanel==='settings'?null:'settings')} style={{background:activePanel==='settings'?'#fff':'#111',color:activePanel==='settings'?'#000':'#fff',border:'1px solid #222',width:42,height:42,borderRadius:12}}>⚙️</button>
   <div style={{marginTop:'auto',paddingBottom:10}}><button onClick={()=>location.href='/'} style={{background:'#0f0',color:'#000',border:0,padding:'5px 8px',borderRadius:6,fontSize:9,fontWeight:'bold'}}>HUB 35</button></div>
  </div>

  <div style={{marginLeft:64,flex:1,paddingBottom:90}}>
   <div style={{display:'flex',alignItems:'center',gap:8,padding:10,background:'#0a0a0a',position:'sticky',top:0,zIndex:10,borderBottom:'1px solid #0f03'}}>
    <span className="spin" style={{fontSize:18}}>🌎</span><div style={{fontWeight:'bold',color:'#0f0',fontSize:11}}>MYGEA V5.1 PHONE FIT</div>
    <button onClick={()=>shareTo('google')} style={{marginLeft:'auto',fontSize:7,border:'1px solid #4285F4',padding:'4px 8px',borderRadius:12,color:'#4285F4',background:'#111'}}>🚦 Google</button>
    <div style={{fontSize:7,border:'1px solid #0f0',padding:'4px 8px',borderRadius:12,color:'#0f0'}}>{phoneFit?'📱 FIT':'5G V5'}</div>
   </div>
   <div onClick={togglePhoneFit} onDoubleClick={goFullScreen} style={{position:'relative',background:'#111',margin:phoneFit?0:10,borderRadius:phoneFit?0:16,overflow:'hidden',border:liveVideo?'2px solid #f00':holo?'2px solid #f0f':'1px solid #222',display:'flex',cursor:'pointer',transition:'all 0.3s'}}>
    <div style={{flex:1,position:'relative'}}>
     <video ref={videoRef} autoPlay muted playsInline onClick={(e)=>{e.stopPropagation(); togglePhoneFit();}} style={{width:'100%',height:live? (phoneFit?'82vh':300):0,background:'#000',objectFit:phoneFit?'contain':fit,transform:`scale(${zoom})`,display:live?'block':'none',transition:'all 0.3s'}}/>
     {!live && <div style={{height:phoneFit?'75vh':260,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:8}}><div style={{fontSize:40}}>📱</div><div style={{color:'#666',fontSize:10,textAlign:'center',padding:'0 10px'}}>Tap Screen Window = Fit to Phone 📱<br/>Double Tap = Full Screen ⛶</div><div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'center'}}><button onClick={(e)=>{e.stopPropagation(); startCamera();}} style={{background:'#0f0',color:'#000',border:0,padding:'10px 14px',borderRadius:8,fontWeight:'bold',fontSize:11}}>START 5G CAM</button><button onClick={(e)=>{e.stopPropagation(); startVideoStream();}} style={{background:'#f00',color:'#fff',border:0,padding:'10px 14px',borderRadius:8,fontWeight:'bold',fontSize:11}}>START STREAM</button><button onClick={(e)=>{e.stopPropagation(); fileInputRef.current.click();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'8px 12px',borderRadius:8,fontSize:10}}>📁 Files</button><button onClick={(e)=>{e.stopPropagation(); videoInputRef.current.click();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'8px 12px',borderRadius:8,fontSize:10}}>🎥 Videos</button></div></div>}
     {live && <><div style={{position:'absolute',top:8,left:8,background:liveVideo?'#f00':'#0f0',color:'#fff',fontSize:8,padding:'4px 8px',borderRadius:12}}>{phoneFit?'📱 PHONE FIT 📱 Tap to Exit':liveVideo?'🔴 LIVE':'📷 5G HOLO'}</div><div style={{position:'absolute',top:8,right:8,background:'rgba(0,0,0,0.7)',borderRadius:20,padding:'4px 8px',fontSize:7,color:'#0f0'}}>{phoneFit?'📱 Fit ON • '+fit:'Fit: '+fit}</div><div style={{position:'absolute',bottom:8,left:'50%',transform:'translateX(-50%)',background:'rgba(0,0,0,0.7)',borderRadius:20,padding:'4px 10px',fontSize:7,color:'#fff'}}>👆 Tap = Phone Fit 📱 • 👆👆 = Full Screen ⛶</div></>}
     {holo &&!live && <div style={{padding:10,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6}}>{Array.from({length:15}).map((_,i)=><div key={i} style={{background:'#111',border:'1px solid #f0f',borderRadius:8,padding:6,textAlign:'center'}}><div style={{fontSize:16}}>👤</div><div style={{fontSize:7,color:'#f0f'}}>HOLO P{i+1}</div></div>)}</div>}
    </div>
    {live && <div style={{width:44,background:'rgba(0,0,0,0.7)',display:'flex',flexDirection:'column',alignItems:'center',gap:6,padding:'8px 4px'}}><button onClick={(e)=>{e.stopPropagation(); togglePlay();}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:36,height:36,borderRadius:8}}>{isPlaying?'⏸️':'▶️'}</button><button onClick={(e)=>{e.stopPropagation(); flipSelfie();}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:36,height:32,borderRadius:8,fontSize:10}}>🤳</button><button onClick={(e)=>{e.stopPropagation(); snapshot();}} style={{background:'#0f0',color:'#000',border:0,width:36,height:32,borderRadius:8}}>🔘</button><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.min(2,z+0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:36,height:28,borderRadius:8,fontSize:9}}>IN+</button><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.max(0.8,z-0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:36,height:28,borderRadius:8,fontSize:9}}>OUT-</button><button onClick={(e)=>{e.stopPropagation(); goFullScreen();}} style={{background:'#4285F4',color:'#fff',border:0,width:36,height:28,borderRadius:8,fontSize:9}}>⛶</button><button onClick={(e)=>{e.stopPropagation(); stopAll();}} style={{background:'#f00',color:'#fff',border:0,width:36,height:28,borderRadius:8,fontSize:8}}>⏺️</button></div>}
   </div>

   {live && <div style={{margin:phoneFit?'0':'0 10px',background:'rgba(0,0,0,0.8)',borderRadius:phoneFit?0:12,padding:'8px 6px',display:'flex',flexWrap:'wrap',gap:5,justifyContent:'center',border:'1px solid #222'}}>
    <button onClick={togglePlay} style={{background:'#111',color:'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:11}}>{isPlaying?'⏸️ Pause':'▶️ Play'}</button>
    <button onClick={()=>{if(videoRef.current) videoRef.current.currentTime+=5}} style={{background:'#111',color:'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:10}}>⏩ Forward</button>
    <button onClick={()=>{if(videoRef.current) videoRef.current.currentTime-=5}} style={{background:'#111',color:'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:10}}>◀️ Reverse</button>
    <button onClick={()=>startVideoStream()} style={{background:'#f00',color:'#fff',border:0,borderRadius:8,padding:'6px 10px',fontSize:10}}>🛑 Record</button>
    <button onClick={stopAll} style={{background:'#333',color:'#fff',border:0,borderRadius:8,padding:'6px 10px',fontSize:10}}>⏺️ Stop</button>
    <button onClick={flipSelfie} style={{background:'#111',color:'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:10}}>🤳 Selfie</button>
    <button onClick={snapshot} style={{background:'#0f0',color:'#000',border:0,borderRadius:8,padding:'6px 10px',fontSize:11}}>🔘 Snapshot</button>
    <button onClick={togglePhoneFit} style={{background:phoneFit?'#0f0':'#111',color:phoneFit?'#000':'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:9}}>📱 {phoneFit?'Exit Phone Fit':'Fit Phone 📱'}</button>
    <button onClick={()=>setFit(fit==="cover"?"contain":"cover")} style={{background:'#111',color:'#fff',border:'1px solid #333',borderRadius:8,padding:'6px 10px',fontSize:9}}>FIT {fit}</button>
    <button onClick={goFullScreen} style={{background:'#4285F4',color:'#fff',border:0,borderRadius:8,padding:'6px 10px',fontSize:9}}>⛶ Full Screen</button>
    <button onClick={()=>shareLinkAction()} style={{background:'#0f0',color:'#000',border:0,borderRadius:8,padding:'6px 10px',fontSize:10}}>🖇️ Share 🔗</button>
   </div>}

   {activePanel==='adverts' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #f00',borderRadius:12,padding:12}}><div style={{color:'#f00',fontWeight:'bold',fontSize:12}}>📺 ADVERTS VIDEO WINDOW PAGE • Google 🚦</div><div style={{background:'#111',borderRadius:10,marginTop:10,height:140,display:'flex',alignItems:'center',justifyContent:'center',border:'1px solid #f00'}}><div style={{textAlign:'center'}}><div style={{fontSize:30}}>📺</div><div style={{fontSize:10,color:'#aaa'}}>Adverts Video {adPlaying?'LIVE':'Paused'} • Google Ads API</div></div></div><div style={{display:'flex',gap:6,marginTop:8}}><button onClick={()=>setAdPlaying(!adPlaying)} style={{background:adPlaying?'#f00':'#111',color:'#fff',border:'1px solid #333',padding:'8px 12px',borderRadius:8,fontSize:10}}>{adPlaying?'⏸️ Pause Ad':'▶️ Play Ad'}</button><button onClick={()=>shareTo('google')} style={{background:'#4285F4',color:'#fff',border:0,padding:'8px 12px',borderRadius:8,fontSize:10}}>🚦 Google Link</button></div></div>}
   {activePanel==='geatune' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #1DB954',borderRadius:12,padding:12}}><div style={{color:'#1DB954',fontWeight:'bold',fontSize:12}}>🎵 GEATUNE LINK 🔗 • Music Platform</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8,marginTop:10}}>{["GeaTune Player API","Upload Music API","My Playlists API","Trending Songs API","Geapple Music Store API","Google Music Link API"].map(s=><button key={s} onClick={()=>{doBackup('geatune_api',s); alert(s+' Linked!');}} style={{background:'#111',border:'1px solid #1DB954',padding:'10px',borderRadius:8,fontSize:10,color:'#fff'}}>{s} 🔗</button>)}</div><button onClick={()=>window.open('/apps/2')} style={{width:'100%',marginTop:10,background:'#1DB954',color:'#000',border:0,padding:10,borderRadius:8,fontWeight:'bold'}}>Open GeaTune Window Page 🔗</button></div>}
   {activePanel==='geapay' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #00D632',borderRadius:12,padding:12}}><div style={{color:'#00D632',fontWeight:'bold',fontSize:12}}>💳 GEAPAY LINK 🔗 • Payment Platform</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8,marginTop:10}}>{["GeaPay Wallet API","Send Money API","Receive Money API","Gea Store Pay API","Transaction History API","Google Pay Link API"].map(s=><button key={s} onClick={()=>{doBackup('geapay_api',s); alert(s+' Linked!');}} style={{background:'#111',border:'1px solid #00D632',padding:'10px',borderRadius:8,fontSize:10,color:'#fff'}}>{s} 🔗</button>)}</div><button onClick={()=>window.open('/apps/3')} style={{width:'100%',marginTop:10,background:'#00D632',color:'#000',border:0,padding:10,borderRadius:8,fontWeight:'bold'}}>Open GeaPay Window Page 🔗</button></div>}
   {activePanel==='theme' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #fa0',borderRadius:12,padding:12}}><div style={{color:'#fa0',fontWeight:'bold',fontSize:12}}>🎨 THEMES • Fixed!</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:10}}>{["HOLO Dark","Neon Green","Ocean Blue","Sunset Orange","Midnight","Geapple"].map(t=><button key={t} onClick={()=>{setTheme(t); doBackup('theme_api',t);}} style={{background:theme===t?'#fa0':'#111',color:theme===t?'#000':'#fff',border:'1px solid #333',padding:12,borderRadius:10,fontSize:10}}>{t} {theme===t?'✓':''}</button>)}</div></div>}
   {activePanel==='legal' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #fff',borderRadius:12,padding:12}}><div style={{fontWeight:'bold',fontSize:12}}>⚖️ LEGAL + NDPA LINK 🔗 • Fixed!</div><div style={{marginTop:10,display:'grid',gap:6}}>{["Terms API","Privacy API","NDPA API","Data Protection API","User Agreement API","Legal Backup JSON","NDPA Backup JSON"].map(s=><button key={s} onClick={()=>{doBackup('legal_ndpa_api',s); alert(s+' Linked!');}} style={{background:'#111',border:'1px solid #fff',padding:'10px',borderRadius:8,fontSize:11,color:'#fff',width:'100%',textAlign:'left'}}>{s} 🔗</button>)}</div><div style={{marginTop:10,fontSize:9,color:'#aaa',background:'#111',padding:10,borderRadius:8}}><div>• CEO: {backupProfilesJSON.ceo}</div><div>• RC: {backupProfilesJSON.rc}</div><div>• {backupProfilesJSON.ecosystem} • {backupProfilesJSON.security}</div><div>• Google: {backupProfilesJSON.google}</div><div>• Files: {backupProfilesJSON.files.json}, {backupProfilesJSON.files.js}, {backupProfilesJSON.files.jsx}</div></div><button onClick={()=>shareTo('google')} style={{width:'100%',marginTop:8,background:'#4285F4',color:'#fff',border:0,padding:10,borderRadius:8,fontWeight:'bold'}}>🚦 Link Platform to Google</button></div>}
   {activePanel==='home' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #0f0',borderRadius:12,padding:12}}><div style={{color:'#0f0',fontWeight:'bold',fontSize:12}}>🏠 HOME + USER MANUAL + JSON BACKUP</div><div style={{display:'flex',gap:10,marginTop:10,alignItems:'center'}}><div style={{width:50,height:50,background:'#0f0',borderRadius:25,display:'flex',alignItems:'center',justifyContent:'center'}}>👤</div><div><div style={{fontSize:13,fontWeight:'bold'}}>Apostle Dr Oladele Mighty Hassan</div><div style={{fontSize:10,color:'#888'}}>CEO Geapple Inc • JSON Backup Active</div><div style={{fontSize:8,color:'#0f0'}}>{backupLog}</div></div></div><div style={{marginTop:10,display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}>{["Edit Profile API","My Posts API","Friends API","Earn API","Privacy API","Notifications API","Users Manual API","Backup JSON","Backup JS","Backup JSX","Phone Fit API"].map(m=><button key={m} onClick={()=>{doBackup('home_api',m); alert(m+' • Provisioned!');}} style={{background:'#111',border:'1px solid #222',padding:'10px',borderRadius:8,fontSize:10,color:'#fff'}}>{m} 🔗</button>)}</div></div>}
   {activePanel==='lang' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #0ff',borderRadius:12,padding:12}}><div style={{color:'#0ff',fontSize:11,fontWeight:'bold'}}>🌐 LANGUAGE INTERPRETER API</div><div style={{display:'flex',gap:6,marginTop:8,flexWrap:'wrap'}}>{["en","yo","ig","ha","pcm","fr","es","zh","ar"].map(l=><button key={l} onClick={()=>{setLang(l); doBackup('lang_api',l);}} style={{background:lang===l?'#0ff':'#111',color:lang===l?'#000':'#fff',border:'1px solid #222',padding:'6px 10px',borderRadius:20,fontSize:10}}>{l}</button>)}</div><div style={{background:'#111',borderRadius:8,padding:10,marginTop:10,fontSize:11,color:'#ccc'}}>{transText}</div><button onClick={translateVoice} style={{width:'100%',marginTop:8,background:'#0ff',color:'#000',border:0,padding:11,borderRadius:10,fontWeight:'bold'}}>🎤 SPEAK</button></div>}
   {!activePanel && <div style={{padding:10}}>
    <div style={{display:'flex',gap:6,marginBottom:10,flexWrap:'wrap'}}><button onClick={()=>fileInputRef.current.click()} style={{background:'#111',border:'1px solid #0f0',color:'#0f0',padding:'8px 12px',borderRadius:20,fontSize:10}}>📁 Upload Files 🖇️</button><button onClick={()=>videoInputRef.current.click()} style={{background:'#111',border:'1px solid #f00',color:'#f00',padding:'8px 12px',borderRadius:20,fontSize:10}}>🎥 Upload Videos 🖇️</button><button onClick={togglePhoneFit} style={{background:phoneFit?'#0f0':'#111',border:'1px solid #0f0',color:phoneFit?'#000':'#0f0',padding:'8px 12px',borderRadius:20,fontSize:10}}>📱 {phoneFit?'Exit Phone Fit':'Fit to Phone 📱'}</button><button onClick={()=>shareTo('google')} style={{background:'#4285F4',color:'#fff',border:0,padding:'8px 12px',borderRadius:20,fontSize:10}}>🚦 Google</button></div>
    {posts.map(p=><div key={p.id} style={{background:'#0a0a0a',border:'1px solid #222',borderRadius:12,padding:12,marginBottom:10}}><div style={{display:'flex',gap:8,alignItems:'center'}}><div style={{width:32,height:32,background:'#0f0',borderRadius:16}}/><div><div style={{fontSize:12,fontWeight:'bold'}}>{p.u}</div><div style={{fontSize:9,color:'#666'}}>5G • HOLO • Phone Fit • Now</div></div></div><div style={{marginTop:8,fontSize:13}}>{p.t}</div><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><button onClick={()=>like(p.id)} style={{background:'#111',border:'1px solid #222',color:p.liked?'#f00':'#888',borderRadius:20,padding:'6px 12px',fontSize:11}}>{p.liked?'❤️':'🤍'} {p.l}</button><button onClick={()=>{setChatId(chatId===p.id?null:p.id); setShareId(null);}} style={{background:chatId===p.id?'#0f0':'#111',border:'1px solid #222',color:chatId===p.id?'#000':'#888',borderRadius:20,padding:'6px 12px',fontSize:11}}>💬 Chat</button><button onClick={()=>shareLinkAction(p.id)} style={{background:'#0f0',border:'1px solid #0f0',color:'#000',borderRadius:20,padding:'6px 14px',fontSize:11,fontWeight:'bold'}}>🖇️ Share Link 🔗</button></div>{shareId===p.id && <div style={{marginTop:10,background:'#111',borderRadius:10,padding:8,display:'flex',gap:6,flexWrap:'wrap'}}><button onClick={()=>shareTo('wa',p.id)} style={{background:'#25D366',color:'#fff',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>WA</button><button onClick={()=>shareTo('fb',p.id)} style={{background:'#1877F2',color:'#fff',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>FB</button><button onClick={()=>shareTo('ig',p.id)} style={{background:'#d62976',color:'#fff',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>IG</button><button onClick={()=>shareTo('tt',p.id)} style={{background:'#000',color:'#fff',border:'1px solid #fff',padding:'6px 10px',borderRadius:6,fontSize:10}}>TT</button><button onClick={()=>shareTo('yt',p.id)} style={{background:'#f00',color:'#fff',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>YT</button><button onClick={()=>shareTo('google',p.id)} style={{background:'#4285F4',color:'#fff',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>🚦 Google</button><button onClick={()=>shareTo('copy',p.id)} style={{background:'#fff',color:'#000',border:0,padding:'6px 10px',borderRadius:6,fontSize:10}}>🖇️ Copy</button></div>}</div>)}<div style={{display:'flex',gap:8,marginTop:10}}><input id="postIn" placeholder="Post..." style={{flex:1,background:'#111',border:'1px solid #222',borderRadius:20,padding:'12px 14px',color:'#fff'}}/><button onClick={()=>{const v=document.getElementById('postIn').value; if(v){setPosts([{id:Date.now(),u:"You",t:v,l:0,liked:false,comments:[],shares:0},...posts]); document.getElementById('postIn').value="";}}} style={{background:'#0f0',color:'#000',border:0,padding:'0 18px',borderRadius:20,fontWeight:'bold'}}>Post</button></div></div>}
   {activePanel==='settings' && <div style={{margin:10,background:'#111',border:'1px solid #fff',borderRadius:12,padding:12}}><div style={{fontWeight:'bold',fontSize:12}}>⚙️ MAIN MENU + JSON/JS/JSX + PHONE FIT</div><div style={{display:'grid',gap:6,marginTop:10}}>{["Backup JSON API","Restore JSON API","Export JSON API","Phone Fit API","Fullscreen API","GeaTune API","GeaPay API","Legal NDPA API","Google Link API","V5.1 Pro Max API"].map(s=><button key={s} onClick={()=>{doBackup('system_api',s); alert(s+' Provisioned!');}} style={{background:'#222',color:'#fff',border:'1px solid #333',padding:'10px',borderRadius:8,fontSize:11,width:'100%',textAlign:'left'}}>{s} 🔗</button>)}</div><div style={{marginTop:8,fontSize:9,color:'#0f0',background:'#000',padding:8,borderRadius:8}}>{backupLog}</div></div>}
  </div>

  <div style={{position:'fixed',bottom:0,left:64,right:0,background:'#0a0a0a',borderTop:'1px solid #222',display:'flex',justifyContent:'space-around',padding:'8px 0',zIndex:20}}>
   <button onClick={()=>shareTo('fb','global')} style={{background:'#1877F2',color:'#fff',border:0,width:30,height:32,borderRadius:8,fontWeight:'bold',fontSize:11}}>f</button>
   <button onClick={()=>shareTo('ig','global')} style={{background:'#d62976',color:'#fff',border:0,width:30,height:32,borderRadius:8,fontSize:9}}>IG</button>
   <button onClick={()=>shareTo('tt','global')} style={{background:'#000',color:'#fff',border:'1px solid #fff',width:30,height:32,borderRadius:8,fontSize:11}}>♪</button>
   <button onClick={()=>shareTo('wa','global')} style={{background:'#25D366',color:'#fff',border:0,width:30,height:32,borderRadius:8,fontSize:9}}>WA</button>
   <button onClick={()=>shareTo('yt','global')} style={{background:'#f00',color:'#fff',border:0,width:30,height:32,borderRadius:8,fontSize:9}}>YT</button>
   <button onClick={()=>shareLinkAction()} style={{background:'#0f0',color:'#000',border:0,width:34,height:32,borderRadius:8,fontWeight:'bold',fontSize:12}}>🖇️</button>
   <button onClick={()=>shareTo('google','global')} style={{background:'#4285F4',color:'#fff',border:0,width:34,height:32,borderRadius:8,fontWeight:'bold',fontSize:9}}>🚦</button>
   <button onClick={togglePhoneFit} style={{background:phoneFit?'#0f0':'#fff',color:phoneFit?'#000':'#000',border:0,width:34,height:32,borderRadius:8,fontWeight:'bold',fontSize:10}}>📱</button>
  </div>
 </div>
 )
}