"use client";
import { useState,useEffect,useRef } from "react";
export default function SuperProMaxV8(){
 const [id,setId]=useState("1"); const [lang,setLang]=useState("en"); const [holo,setHolo]=useState(false);
 const [live,setLive]=useState(false); const [zoom,setZoom]=useState(1); const [fit,setFit]=useState("cover"); const [phoneFit,setPhoneFit]=useState(false);
 const [facing,setFacing]=useState("user"); const [activePanel,setActivePanel]=useState(null);
 const [homeFolder,setHomeFolder]=useState(false); const [screenFolder,setScreenFolder]=useState(false); const [shareFolder,setShareFolder]=useState(false);
 const [transText,setTransText]=useState("NINO Language Ready - Tap 🎤 Speak English → Hear 10 Locals"); const [satNumber,setSatNumber]=useState(""); const [satCall,setSatCall]=useState(false);
 const [cart,setCart]=useState([]); const [balance,setBalance]=useState(85000); const [payMethod,setPayMethod]=useState("Paystack");
 const videoRef=useRef(null); const canvasRef=useRef(null);
 const [posts,setPosts]=useState([{id:1,u:"Apostle Dr Mighty",t:"V8 SUPER PRO MAX 🌍 HOLO 25 + STORE + PAY + SAT Dial + NINO 10 Langs LIVE!",l:152,liked:false,comments:["Weldone CTO!"],shares:12}]);
 const NINO_LANGS=[{k:"en",l:"English",f:"🇺🇸"},{k:"yo",l:"Yoruba",f:"🇳🇬"},{k:"ig",l:"Igbo",f:"🇳🇬"},{k:"ha",l:"Hausa",f:"🇳🇬"},{k:"pcm",l:"Pidgin",f:"🇳🇬"},{k:"fr",l:"French",f:"🇫🇷"},{k:"es",l:"Spanish",f:"🇪🇸"},{k:"zh",l:"Chinese",f:"🇨🇳"},{k:"ar",l:"Arabic",f:"🇸🇦"},{k:"pt",l:"Portuguese",f:"🇵🇹"}];
 const HOLO_USERS=Array.from({length:25}).map((_,i)=>({id:i+1,name:`User ${i+1}`,flag:["🇳🇬","🇺🇸","🇬🇧","🇫🇷","🇪🇸","🇨🇳","🇸🇦","🇩🇪","🇮🇳","🇧🇷"][i%10],avatar:["👨‍💼","👩‍💻","👨‍🎤","👩‍🔬","👨‍🚀"][i%5]}));
 const STORE_ITEMS=[{n:"5G Phone",p:120000},{n:"SAT Device",p:85000},{n:"HOLO Glasses",p:150000},{n:"Geapple Watch",p:45000},{n:"MYGEA App Pro",p:5000},{n:"GEACONNECT Pro",p:3000}];
 useEffect(()=>{ const p=typeof window!=='undefined'? window.location.pathname.split('/').pop():null; if(p &&!isNaN(p)) setId(p); },[]);
 const startCam=async()=>{ try{ const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:1920},audio:true}); if(videoRef.current){videoRef.current.srcObject=s; videoRef.current.play(); setLive(true);} }catch{alert("Allow Camera!");}};
 const stopCam=()=>{ if(videoRef.current?.srcObject) videoRef.current.srcObject.getTracks().forEach(t=>t.stop()); setLive(false); };
 const togglePhoneFit=()=>{ setPhoneFit(!phoneFit); setFit(!phoneFit?"contain":"cover"); };
 const snapshot=()=>{ if(!videoRef.current ||!canvasRef.current) return; const c=canvasRef.current; c.width=videoRef.current.videoWidth; c.height=videoRef.current.videoHeight; c.getContext('2d').drawImage(videoRef.current,0,0); const a=document.createElement('a'); a.href=c.toDataURL("image/png"); a.download=`V8_${Date.now()}.png`; a.click(); };
 const translateVoice=()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR){alert("Use Chrome!");return;} const rec=new SR(); rec.lang='en-US'; rec.onstart=()=>setTransText("🎤 Listening..."); rec.onresult=(e)=>{ const txt=e.results[0][0].transcript; const map={yo:`Yoruba: ${txt} - Bawo ni`,ig:`Igbo: ${txt} - Kedu`,ha:`Hausa: ${txt} - Sannu`,pcm:`Pidgin: ${txt} - How you dey`,fr:`French: ${txt} -> Bonjour`,es:`Spanish: ${txt} -> Hola`,zh:`Chinese: ${txt} -> Ni hao`,ar:`Arabic: ${txt} -> Salam`,pt:`Portuguese: ${txt} -> Ola`}; const tr=map[lang]||txt; setTransText(`✅ "${txt}" → ${tr}`); speechSynthesis.speak(new SpeechSynthesisUtterance(tr)); }; rec.start(); };
 const dial=(d)=> setSatNumber(prev=> (prev+d).slice(0,15));
 const makeSatCall=()=>{ if(!satNumber) return alert("Enter number!"); setSatCall(true); alert(`🤙 SAT Calling ${satNumber} via Geapple SAT... Free Call Connected!`); };
 if(id!=="1") return <div style={{background:'#000',color:'#fff',minHeight:'100vh',padding:20,textAlign:'center'}}><h2 style={{color:'#0f0'}}>APP {id} - Built Along V8 Ecosystem</h2><button onClick={()=>location.href='/apps/1'} style={{background:'#0f0',color:'#000',padding:12,borderRadius:10,marginTop:10}}>Go V8 SUPER PRO MAX</button></div>;
 return(
 <div style={{background:'#000',minHeight:'100vh',color:'#fff',display:'flex',fontFamily:'sans-serif'}}>
  <canvas ref={canvasRef} style={{display:'none'}}/>
  <div style={{width:62,background:'#0a0a0a',borderRight:'1px solid #0f03',display:'flex',flexDirection:'column',alignItems:'center',gap:10,padding:'10px 0',position:'fixed',height:'100vh',zIndex:30}}>
   <div style={{width:46,height:46,background:'#111',borderRadius:12,display:'flex',alignItems:'center',justifyContent:'center',border:'1px solid #0f0'}}>🌍</div>
   <button onClick={()=>{setHomeFolder(!homeFolder); setScreenFolder(false);}} style={{background:homeFolder?'#0f0':'#111',border:'1px solid #222',width:44,height:44,borderRadius:12}} title="Home Folder - All Tools">🏡</button>
   <button onClick={()=>setShareFolder(!shareFolder)} style={{background:shareFolder?'#0f0':'#111',border:'1px solid #222',width:44,height:44,borderRadius:12}}>💠</button>
   <div style={{marginTop:'auto'}}><button onClick={()=>location.href='/'} style={{background:'#0f0',color:'#000',border:0,padding:'5px 8px',borderRadius:6,fontSize:9,fontWeight:'bold'}}>HUB 35</button></div>
  </div>
  {homeFolder && <div style={{position:'fixed',left:62,top:0,bottom:0,width:220,background:'#0f0f0f',borderRight:'1px solid #0f03',zIndex:25,padding:12,overflowY:'auto'}}>
   <div style={{fontWeight:'bold',fontSize:12,color:'#0f0'}}>📂 HOME FOLDER - ALL VERTICAL TOOLS</div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:10}}>
    <button onClick={()=>{setActivePanel('camera'); startCam(); setHomeFolder(false);}} style={{background:'#111',border:'1px solid #222',padding:10,borderRadius:10,fontSize:10}}>📷<br/>Cam</button>
    <button onClick={()=>setActivePanel('video')} style={{background:'#111',border:'1px solid #222',padding:10,borderRadius:10,fontSize:10}}>📹<br/>Video</button>
    <button onClick={()=>{setHolo(!holo); setActivePanel('holo');}} style={{background:holo?'#f0f':'#111',border:'1px solid #222',padding:10,borderRadius:10,fontSize:10}}>👁️<br/>HOLO 25</button>
    <button onClick={()=>setActivePanel('store')} style={{background:'#fd0',border:'1px solid #fd0',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>🏪<br/>STORE</button>
    <button onClick={()=>setActivePanel('pay')} style={{background:'#0ef',border:'1px solid #0ef',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>💳<br/>PAY</button>
    <button onClick={()=>setActivePanel('sat')} style={{background:'#0f0',border:'1px solid #0f0',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>🤙<br/>SAT Dial</button>
    <button onClick={()=>setActivePanel('lang')} style={{background:'#111',border:'1px solid #0ff',padding:10,borderRadius:10,fontSize:10}}>🌐<br/>NINO 10</button>
    <button onClick={()=>setActivePanel('theme')} style={{background:'#111',border:'1px solid #fa0',padding:10,borderRadius:10,fontSize:10}}>🎨<br/>Theme</button>
   </div>
   <button onClick={()=>setHomeFolder(false)} style={{width:'100%',marginTop:10,background:'#222',color:'#fff',border:0,padding:8,borderRadius:8}}>Close Folder</button>
  </div>}
  <div style={{marginLeft:62,flex:1,paddingBottom:90}}>
   <div style={{display:'flex',alignItems:'center',gap:8,padding:10,background:'#0a0a0a',position:'sticky',top:0,zIndex:10,borderBottom:'1px solid #0f03'}}>
    <span>🌎</span><div style={{fontWeight:'bold',color:'#0f0',fontSize:11}}>MYGEA V8 SUPER PRO MAX + STORE + PAY + HOLO 25 + SAT DIAL + NINO 10</div>
    <div style={{marginLeft:'auto',display:'flex',gap:6}}><div style={{fontSize:7,border:'1px solid #0f0',padding:'4px 8px',borderRadius:12,color:'#0f0'}}>5G V8</div></div>
   </div>
   <div onClick={togglePhoneFit} style={{position:'relative',background:'#111',margin:phoneFit?0:10,borderRadius:phoneFit?0:16,overflow:'hidden',border:'1px solid #222',cursor:'pointer'}}>
    <video ref={videoRef} autoPlay muted playsInline style={{width:'100%',height:live? (phoneFit?'78vh':300):0,background:'#000',objectFit:fit,transform:`scale(${zoom})`,display:live?'block':'none'}}/>
    {!live && <div style={{height:phoneFit?'70vh':260,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:8}}><div style={{fontSize:36}}>📱</div><div style={{color:'#666',fontSize:10,textAlign:'center'}}>Tap Window = Fit Phone 📱<br/>... button = Video Tools</div><div style={{display:'flex',gap:6}}><button onClick={(e)=>{e.stopPropagation(); startCam();}} style={{background:'#0f0',color:'#000',border:0,padding:'9px 14px',borderRadius:8,fontWeight:'bold',fontSize:11}}>START 5G CAM</button><button onClick={(e)=>{e.stopPropagation(); setScreenFolder(true);}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'9px 14px',borderRadius:8,fontSize:11}}>... Tools</button></div></div>}
    {live && <div style={{position:'absolute',top:8,left:8,background:'#0f0',color:'#000',fontSize:8,padding:'4px 8px',borderRadius:12}}>{phoneFit?'📱 FIT':'🔴 LIVE'} • Tap to Fit</div>}
    <div style={{position:'absolute',top:8,right:8,display:'flex',gap:6}}><button onClick={(e)=>{e.stopPropagation(); setScreenFolder(!screenFolder);}} style={{background:'rgba(0,0,0,0.7)',color:'#fff',border:'1px solid #333',width:36,height:32,borderRadius:8,fontSize:14}}>{screenFolder?'✕':'...'}</button></div>
    {screenFolder && <div style={{position:'absolute',right:8,top:44,background:'#0a0a0a',border:'1px solid #0f0',borderRadius:12,padding:6,display:'flex',flexDirection:'column',gap:6,zIndex:20}}><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.min(2,z+0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:80,height:32,borderRadius:8,fontSize:10}}>🔍+ IN</button><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.max(0.8,z-0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:80,height:32,borderRadius:8,fontSize:10}}>🔍- OUT</button><button onClick={(e)=>{e.stopPropagation(); snapshot();}} style={{background:'#0f0',color:'#000',border:0,width:80,height:32,borderRadius:8,fontSize:10}}>🔘 SNAP</button><button onClick={(e)=>{e.stopPropagation(); stopCam();}} style={{background:'#f00',color:'#fff',border:0,width:80,height:32,borderRadius:8,fontSize:10}}>⏺️ STOP</button><button onClick={(e)=>{e.stopPropagation(); setFit(fit==="cover"?"contain":"cover");}} style={{background:'#111',color:'#fff',border:'1px solid #333',width:80,height:32,borderRadius:8,fontSize:9}}>FIT {fit}</button><button onClick={(e)=>{e.stopPropagation(); togglePhoneFit();}} style={{background:'#0f0',color:'#000',border:0,width:80,height:32,borderRadius:8,fontSize:10}}>📱 Phone Fit</button></div>}
   </div>
   {activePanel==='store' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #fd0',borderRadius:12,padding:12}}><div style={{color:'#fd0',fontWeight:'bold'}}>🏪 GEA STORE Marketplace - All Apps & Products + Upload System</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:10}}>{STORE_ITEMS.map(it=><div key={it.n} style={{background:'#111',border:'1px solid #333',borderRadius:10,padding:10}}><div style={{fontSize:11,fontWeight:'bold'}}>{it.n}</div><div style={{fontSize:10,color:'#fd0'}}>₦{it.p.toLocaleString()}</div><button onClick={()=>{setCart([...cart,it]); alert(`${it.n} Added!`);}} style={{width:'100%',marginTop:6,background:'#fd0',color:'#000',border:0,padding:'6px',borderRadius:6,fontSize:10,fontWeight:'bold'}}>Add 🛒</button></div>)}</div><div style={{marginTop:8,fontSize:10}}>Cart: {cart.length} items • Total: ₦{cart.reduce((s,i)=>s+i.p,0).toLocaleString()}</div></div>}
   {activePanel==='pay' && <div style={{margin:10,background:'#0a0a0a',border:'2px solid #0ef',borderRadius:12,padding:12}}><div style={{color:'#0ef',fontWeight:'bold'}}>💳 GEA PAY - GPay + Paystack + Flutterwave + Monnify</div><div style={{display:'flex',gap:6,marginTop:8,flexWrap:'wrap'}}>{["Paystack","Flutterwave","Monnify","GPay"].map(m=><button key={m} onClick={()=>setPayMethod(m)} style={{background:payMethod===m?'#0ef':'#111',color:payMethod===m?'#000':'#fff',border:'1px solid #0ef',padding:'8px 12px',borderRadius:20,fontSize:10,fontWeight:'bold'}}>{m}</button>)}</div><div style={{background:'#111',padding:10,borderRadius:8,marginTop:8}}><div style={{fontSize:12}}>Balance: ₦{balance.toLocaleString()}</div><div style={{fontSize:9,color:'#aaa'}}>Cart Total: ₦{cart.reduce((s,i)=>s+i.p,0).toLocaleString()} • Method: {payMethod}</div></div><button onClick={()=>{setBalance(b=>b-cart.reduce((s,i)=>s+i.p,0)); setCart([]); alert(`✅ Payment Confirmed via ${payMethod} - CEO Dashboard Notified!`);}} style={{width:'100%',marginTop:8,background:'#0ef',color:'#000',border:0,padding:'10px',borderRadius:8,fontWeight:'bold'}}>Pay with {payMethod} ✅</button><div style={{marginTop:8,fontSize:9,color:'#0f0',background:'#000',padding:8,borderRadius:8}}>CEO Dashboard • Notification • Confirmation Linked • RC:9882150</div></div>}
   {activePanel==='sat' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #0f0',borderRadius:12,padding:12}}><div style={{color:'#0f0',fontWeight:'bold'}}>🤙 SAT Calls - Dial Numbers to Call Family & Friends</div><div style={{background:'#111',borderRadius:12,padding:12,marginTop:8,textAlign:'center'}}><div style={{background:'#000',border:'1px solid #0f0',borderRadius:8,padding:'12px',fontSize:20,letterSpacing:'4px',color:'#0f0',minHeight:24}}>{satNumber||"Enter Number"}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:12}}>{["1","2","3","4","5","6","7","8","9","*","0","#"].map(d=><button key={d} onClick={()=>dial(d)} style={{background:'#222',color:'#fff',border:'1px solid #333',padding:'16px',borderRadius:12,fontSize:18,fontWeight:'bold'}}>{d}</button>)}</div><div style={{display:'flex',gap:8,marginTop:10}}><button onClick={()=>setSatNumber("")} style={{flex:1,background:'#333',color:'#fff',border:0,padding:'12px',borderRadius:10}}>Clear</button><button onClick={makeSatCall} style={{flex:2,background:satCall?'#f00':'#0f0',color:satCall?'#fff':'#000',border:0,padding:'12px',borderRadius:10,fontWeight:'bold'}}>{satCall?'End Call 🤙':'Call 🤙 SAT Free'}</button></div><div style={{fontSize:9,color:'#888',marginTop:8}}>SAT Free Calls Online/Offline via Geapple SAT • CEO: Apostle Mighty</div></div></div>}
   {activePanel==='holo' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #f0f',borderRadius:12,padding:12}}><div style={{color:'#f0f',fontWeight:'bold'}}>👁️ HOLO 25 + Sensors + Projector + Conference Windows</div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6,marginTop:10}}>{HOLO_USERS.map(u=><div key={u.id} style={{background:'#111',border:'1px solid #f0f',borderRadius:10,padding:6,textAlign:'center'}}><div style={{fontSize:16}}>{u.avatar}</div><div style={{fontSize:8,fontWeight:'bold'}}>P{u.id}</div><div style={{fontSize:10}}>{u.flag}</div><div style={{height:6,background:'radial-gradient(ellipse,#000,#f0f)',borderRadius:'50%',marginTop:4}}/><div style={{fontSize:5,color:'#f0f',marginTop:2}}>3D Projector</div></div>)}</div><div style={{marginTop:10,display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><button style={{background:'#111',border:'1px solid #f0f',padding:'10px',borderRadius:8,fontSize:10,color:'#fff'}}>🎥 Screen Share</button><button style={{background:'#f0f',color:'#000',border:0,padding:'10px',borderRadius:8,fontSize:10,fontWeight:'bold'}}>🔴 Record Conference</button></div></div>}
   {activePanel==='lang' && <div style={{margin:10,background:'#0a0a0a',border:'1px solid #0ff',borderRadius:12,padding:12}}><div style={{color:'#0ff',fontWeight:'bold'}}>🌐 NINO Language Voice Translation - 10 Languages</div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6,marginTop:8}}>{NINO_LANGS.map(L=><button key={L.k} onClick={()=>setLang(L.k)} style={{background:lang===L.k?'#0ff':'#111',color:lang===L.k?'#000':'#fff',border:'1px solid #222',padding:'8px 6px',borderRadius:10,fontSize:9}}>{L.f}<br/>{L.l}</button>)}</div><div style={{background:'#111',borderRadius:8,padding:10,marginTop:10,fontSize:11,minHeight:40,border:'1px solid #0ff'}}>{transText}</div><button onClick={translateVoice} style={{width:'100%',marginTop:8,background:'#0ff',color:'#000',border:0,padding:12,borderRadius:10,fontWeight:'bold'}}>🎤 SPEAK ENGLISH → HEAR {lang.toUpperCase()} ({NINO_LANGS.find(l=>l.k===lang)?.l})</button><div style={{fontSize:8,color:'#0f0',marginTop:6}}>✅ Fixed: Speaking English and hear local + international up to 10 languages active!</div></div>}
   <div style={{padding:10,paddingRight:50}}>
    {posts.map(p=><div key={p.id} style={{background:'#0a0a0a',border:'1px solid #222',borderRadius:12,padding:12,marginBottom:10}}><div style={{display:'flex',gap:8}}><div style={{width:32,height:32,background:'#0f0',borderRadius:16}}/><div><div style={{fontSize:12,fontWeight:'bold'}}>{p.u}</div><div style={{fontSize:9,color:'#666'}}>V8 SUPER PRO MAX • Now</div></div></div><div style={{marginTop:8,fontSize:13}}>{p.t}</div><div style={{display:'flex',gap:8,marginTop:10}}><button onClick={()=>{}} style={{background:'#111',border:'1px solid #222',borderRadius:20,padding:'6px 12px',fontSize:11}}>❤️ {p.l}</button><button onClick={()=>{}} style={{background:'#111',border:'1px solid #222',borderRadius:20,padding:'6px 12px',fontSize:11}}>💬 Chat</button><button onClick={()=>{navigator.clipboard.writeText(window.location.href); alert('🔗 Copied!');}} style={{background:'#0f0',color:'#000',borderRadius:20,padding:'6px 14px',fontSize:11,fontWeight:'bold'}}>🖇️ Share 🔗</button></div></div>)}
   </div>
  </div>
  <div style={{position:'fixed',bottom:0,left:62,right:0,background:'#0a0a0a',borderTop:'1px solid #222',zIndex:20,padding:'6px'}}>
   {!shareFolder? <div style={{display:'flex',justifyContent:'space-around',alignItems:'center'}}><div style={{fontSize:8,color:'#666'}}>V8 SUPER PRO MAX</div><button onClick={()=>setShareFolder(true)} style={{background:'#0f0',color:'#000',border:0,padding:'8px 20px',borderRadius:20,fontWeight:'bold',fontSize:11}}>💠 Shared Links - TikTok IG YT LinkedIn 🔗 Tap</button></div> :
   <div><div style={{display:'flex',justifyContent:'space-between',marginBottom:6}}><div style={{fontSize:10,fontWeight:'bold'}}>📂 SHARED LINKS - TikTok IG YT LinkedIn + Platforms UI Icons</div><button onClick={()=>setShareFolder(false)} style={{background:'#222',color:'#fff',border:0,padding:'4px 8px',borderRadius:6,fontSize:9}}>✕</button></div><div style={{display:'flex',justifyContent:'space-around'}}><button onClick={()=>window.open('https://facebook.com')} style={{background:'#1877F2',color:'#fff',border:0,width:36,height:32,borderRadius:8}}>f</button><button onClick={()=>window.open('https://instagram.com')} style={{background:'#d62976',color:'#fff',border:0,width:36,height:32,borderRadius:8,fontSize:9}}>IG</button><button onClick={()=>window.open('https://tiktok.com')} style={{background:'#000',color:'#fff',border:'1px solid #fff',width:36,height:32,borderRadius:8}}>♪</button><button onClick={()=>window.open('https://wa.me')} style={{background:'#25D366',color:'#fff',border:0,width:36,height:32,borderRadius:8,fontSize:9}}>WA</button><button onClick={()=>window.open('https://youtube.com')} style={{background:'#f00',color:'#fff',border:0,width:36,height:32,borderRadius:8,fontSize:9}}>YT</button><button onClick={()=>window.open('https://linkedin.com')} style={{background:'#0A66C2',color:'#fff',border:0,width:36,height:32,borderRadius:8,fontSize:9}}>in</button><button onClick={()=>{navigator.clipboard.writeText(window.location.href); alert('🔗 Copied!');}} style={{background:'#0f0',color:'#000',border:0,width:36,height:32,borderRadius:8,fontWeight:'bold'}}>🖇️</button><button onClick={()=>window.open('https://google.com/search?q=Geapple')} 
style={{background:'#4285F4',color:'#fff',border:0,width:36,height:32,borderRadius:8,fontSize:9}}>🚦</button></div></div>}
  </div>
 </div>
)
}