"use client";
import { useState,useEffect,useRef } from "react";
import { db } from "../../../lib/firebase.js";
import { collection, addDoc, onSnapshot, query, orderBy } from "firebase/firestore";

export default function V10FirebaseRealtime(){
 const [id,setId]=useState("1"); const [lang,setLang]=useState("en"); const [holo,setHolo]=useState(false);
 const [live,setLive]=useState(false); const [isPlaying,setIsPlaying]=useState(true); const [zoom,setZoom]=useState(1);
 const [fit,setFit]=useState("cover"); const [phoneFit,setPhoneFit]=useState(false); const [facing,setFacing]=useState("user");
 const [activePanel,setActivePanel]=useState(null); const [homeFolder,setHomeFolder]=useState(false); const [screenFolder,setScreenFolder]=useState(false);
 const [shareFolder,setShareFolder]=useState(false); const [chatId,setChatId]=useState(null); const [satNumber,setSatNumber]=useState("");
 const [cart,setCart]=useState([]); const [balance,setBalance]=useState(85000); const [payMethod,setPayMethod]=useState("Paystack");
 const [transText,setTransText]=useState("NINO RealTime Firebase Ready"); const videoRef=useRef(null); const canvasRef=useRef(null);
 const [posts,setPosts]=useState([]);

 useEffect(()=>{ const p=window.location.pathname.split('/').pop(); if(p &&!isNaN(p)) setId(p);
  if(!db) return; const q=query(collection(db,"mygea_posts"), orderBy("createdAt","desc"));
  const unsub=onSnapshot(q,(snap)=>{ if(!snap.empty){ setPosts(snap.docs.map(d=>({id:d.id,...d.data()}))); }});
  return ()=>unsub();
 },[]);

 const startCam=async()=>{ try{ const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing,width:1920},audio:true}); if(videoRef.current){videoRef.current.srcObject=s; await videoRef.current.play(); setLive(true);} }catch{alert("Allow Camera");}};
 const stopCam=()=>{ if(videoRef.current?.srcObject) videoRef.current.srcObject.getTracks().forEach(t=>t.stop()); setLive(false); };
 const togglePlay=()=>{ if(!videoRef.current) return; isPlaying?videoRef.current.pause():videoRef.current.play(); setIsPlaying(!isPlaying); };
 const forward=()=>{ if(videoRef.current) videoRef.current.currentTime+=5; }; const rewind=()=>{ if(videoRef.current) videoRef.current.currentTime-=5; };
 const flip=()=>{ setFacing(f=>f==="user"?"environment":"user"); setTimeout(()=>{if(live) startCam();},500); };
 const toggleFit=()=>{ setPhoneFit(!phoneFit); setFit(!phoneFit?"contain":"cover"); };
 const snap=()=>{ if(!videoRef.current ||!canvasRef.current) return; const c=canvasRef.current; c.width=videoRef.current.videoWidth; c.height=videoRef.current.videoHeight; c.getContext('2d').drawImage(videoRef.current,0,0); const a=document.createElement('a'); a.href=c.toDataURL("image/png"); a.download=`V10_${Date.now()}.png`; a.click(); };

 const likeReal=async(pid)=>{ if(!db) return; await addDoc(collection(db,"likes"),{postId:pid, user:"geappleadmin", createdAt: new Date()}); };
 const chatReal=async(pid)=>{ const el=document.getElementById(`c-${pid}`); if(!el?.value ||!db) return; await addDoc(collection(db,"chats",String(pid),"messages"),{text:el.value,user:"You",createdAt:new Date()}); el.value=""; };
 const shareReal=(pl,pid)=>{ const url=window.location.href+`?post=${pid}`; const txt=`MYGEA V10 ${url}`; if(pl==='wa') window.open(`https://wa.me/?text=${encodeURIComponent(txt)}`); if(pl==='fb') window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`); if(pl==='ig') window.open(`https://instagram.com`); if(pl==='tt') window.open(`https://tiktok.com`); if(pl==='yt') window.open(`https://youtube.com`); if(pl==='li') window.open(`https://linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`); if(pl==='copy'){navigator.clipboard.writeText(url); alert('🔗 Copied '+url);} };

 const payReal=async()=>{ const total=cart.reduce((s,i)=>s+i.p,0)||5000; if(!db) return alert("Firebase not ready"); await addDoc(collection(db,"payments"),{amount:total,method:payMethod,status:"Pending",cart,createdAt:new Date()}); alert(`✅ ${payMethod} Payment ₦${total} Sent to CEO Dashboard - Firebase RealTime!`); setBalance(b=>b-total); setCart([]); };
 const dial=(d)=> setSatNumber(s=>(s+d).slice(0,15));
 const callReal=async()=>{ if(!satNumber) return; if(db) await addDoc(collection(db,"sat_calls"),{number:satNumber, status:"Calling", createdAt:new Date()}); window.open(`tel:${satNumber}`); };
 const translateReal=()=>{ const SR=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SR) return; const r=new SR(); r.lang='en-US'; r.onresult=(e)=>{ const txt=e.results[0][0].transcript; const map={yo:`Yoruba: ${txt}`,ig:`Igbo: ${txt}`,ha:`Hausa: ${txt}`,pcm:`Pidgin: ${txt}`,fr:`French: ${txt}`,es:`Spanish: ${txt}`,zh:`Chinese: ${txt}`,ar:`Arabic: ${txt}`,pt:`Portuguese: ${txt}`}; const tr=map[lang]||txt; setTransText(tr); speechSynthesis.speak(new SpeechSynthesisUtterance(tr)); }; r.start(); };

 if(id!=="1") return <div style={{background:'#000',color:'#fff',minHeight:'100vh',padding:20,textAlign:'center'}}><h2 style={{color:'#0f0'}}>APP {id}</h2><button onClick={()=>location.href='/apps/1'} style={{background:'#0f0',color:'#000',padding:12,borderRadius:10}}>Go V10</button></div>;

 return(
 <div style={{background:'#000',minHeight:'100vh',color:'#fff',display:'flex',fontFamily:'sans-serif'}}>
  <canvas ref={canvasRef} style={{display:'none'}}/>
  <div style={{width:62,background:'#0a0a0a',borderRight:'1px solid #0f03',display:'flex',flexDirection:'column',alignItems:'center',gap:10,padding:'10px 0',position:'fixed',height:'100vh',zIndex:30}}>
   <div style={{width:46,height:46,background:'#111',borderRadius:12,display:'flex',alignItems:'center',justifyContent:'center',border:'1px solid #0f0'}}>🌍</div>
   <button onClick={()=>setHomeFolder(!homeFolder)} style={{background:homeFolder?'#0f0':'#111',border:'1px solid #222',width:44,height:44,borderRadius:12}}>🏡</button>
   <button onClick={()=>setShareFolder(!shareFolder)} style={{background:shareFolder?'#0f0':'#111',border:'1px solid #222',width:44,height:44,borderRadius:12}}>💠</button>
   <button onClick={()=>location.href='/'} style={{background:'#0f0',color:'#000',border:0,padding:'5px 8px',borderRadius:6,fontSize:9,fontWeight:'bold',marginTop:'auto'}}>HUB 35</button>
  </div>
  {homeFolder && <div style={{position:'fixed',left:62,top:0,bottom:0,width:230,background:'#0f0f0f',borderRight:'1px solid #0f03',zIndex:25,padding:12,overflowY:'auto'}}>
   <div style={{fontWeight:'bold',fontSize:12,color:'#0f0'}}>🏡 ALL TOOLS + REALTIME API</div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:10}}>
    <button onClick={()=>{setActivePanel('camera'); startCam();}} style={{background:'#111',border:'1px solid #222',padding:10,borderRadius:10,fontSize:10}}>📷 Cam</button>
    <button onClick={()=>setActivePanel('pay')} style={{background:'#0ef',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>💳 PAY</button>
    <button onClick={()=>setActivePanel('store')} style={{background:'#fd0',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>🏪 STORE</button>
    <button onClick={()=>{setHolo(!holo); setActivePanel('holo');}} style={{background:'#f0f',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>👁️ HOLO 25</button>
    <button onClick={()=>setActivePanel('sat')} style={{background:'#0f0',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>🤙 SAT</button>
    <button onClick={()=>setActivePanel('lang')} style={{background:'#0ff',padding:10,borderRadius:10,fontSize:10,color:'#000',fontWeight:'bold'}}>🌐 NINO</button>
   </div>
   <button onClick={()=>setHomeFolder(false)} style={{width:'100%',marginTop:10,background:'#222',color:'#fff',border:0,padding:8,borderRadius:8}}>Close</button>
  </div>}
  <div style={{marginLeft:62,flex:1,paddingBottom:90}}>
   <div style={{display:'flex',alignItems:'center',gap:8,padding:10,background:'#0a0a0a',position:'sticky',top:0,zIndex:10,borderBottom:'1px solid #0f03'}}><span>🌎</span><div style={{fontWeight:'bold',color:'#0f0',fontSize:11}}>MYGEA V10 FIREBASE REALTIME</div><div style={{marginLeft:'auto',fontSize:8,border:'1px solid #0f0',padding:'4px 8px',borderRadius:12,color:'#0f0'}}>Firebase: {db?'Connected ✅':'Offline'}</div></div>
   <div onClick={toggleFit} style={{position:'relative',background:'#111',margin:phoneFit?0:10,borderRadius:phoneFit?0:16,overflow:'hidden',border:'1px solid #222',cursor:'pointer'}}>
    <video ref={videoRef} autoPlay muted playsInline style={{width:'100%',height:live?(phoneFit?'78vh':320):0,background:'#000',objectFit:fit,transform:`scale(${zoom})`,display:live?'block':'none'}}/>
    {!live && <div style={{height:260,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:8}}><div style={{fontSize:36}}>📱</div><div style={{color:'#666',fontSize:10}}>Tap = Phone Fit •... = All Tools</div><button onClick={(e)=>{e.stopPropagation(); startCam();}} style={{background:'#0f0',color:'#000',border:0,padding:'10px 16px',borderRadius:8,fontWeight:'bold'}}>START 5G CAM</button></div>}
    <div style={{position:'absolute',top:8,right:8}}><button onClick={(e)=>{e.stopPropagation(); setScreenFolder(!screenFolder);}} style={{background:'rgba(0,0,0,0.8)',color:'#fff',border:'1px solid #0f0',width:42,height:34,borderRadius:10,fontSize:16,fontWeight:'bold'}}>{screenFolder?'✕':'...'}</button></div>
    {screenFolder && <div style={{position:'absolute',right:8,top:48,background:'#0a0a0a',border:'2px solid #0f0',borderRadius:14,padding:8,display:'flex',flexDirection:'column',gap:6,zIndex:20}}><button onClick={(e)=>{e.stopPropagation(); togglePlay();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'10px',borderRadius:10}}>{isPlaying?'⏸️ Pause':'▶️ Play'}</button><button onClick={(e)=>{e.stopPropagation(); forward();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'10px',borderRadius:10}}>⏩ Forward</button><button onClick={(e)=>{e.stopPropagation(); rewind();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'10px',borderRadius:10}}>◀️ Rewind</button><button onClick={(e)=>{e.stopPropagation(); flip();}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'10px',borderRadius:10}}>🤳 Selfie</button><button onClick={(e)=>{e.stopPropagation(); snap();}} style={{background:'#0f0',color:'#000',border:0,padding:'10px',borderRadius:10,fontWeight:'bold'}}>🔘 SNAP</button><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.min(2,z+0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'8px',borderRadius:8}}>🔍+ IN</button><button onClick={(e)=>{e.stopPropagation(); setZoom(z=>Math.max(0.8,z-0.2));}} style={{background:'#111',color:'#fff',border:'1px solid #333',padding:'8px',borderRadius:8}}>🔍- OUT</button><button onClick={(e)=>{e.stopPropagation(); stopCam();}} style={{background:'#f00',color:'#fff',border:0,padding:'10px',borderRadius:10,fontWeight:'bold'}}>⏺️ STOP</button></div>}
   </div>
   {activePanel==='sat' && <div style={{margin:10,background:'#0a0a0a',border:'2px solid #0f0',borderRadius:12,padding:12}}><div style={{color:'#0f0',fontWeight:'bold'}}>🤙 SAT RealTime Firebase Dial</div><div style={{background:'#111',borderRadius:12,padding:12,marginTop:8,textAlign:'center'}}><div style={{background:'#000',border:'2px solid #0f0',borderRadius:10,padding:'14px',fontSize:22,letterSpacing:'4px',color:'#0f0'}}>{satNumber||"Enter Number"}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:12}}>{["1","2","3","4","5","6","7","8","9","*","0","#"].map(d=><button key={d} onClick={()=>dial(d)} style={{background:'#222',color:'#fff',border:'1px solid #333',padding:'18px',borderRadius:12,fontSize:20,fontWeight:'bold'}}>{d}</button>)}</div><div style={{display:'flex',gap:8,marginTop:12}}><button onClick={()=>setSatNumber("")} style={{flex:1,background:'#333',color:'#fff',border:0,padding:'14px',borderRadius:10}}>Clear</button><button onClick={callReal} style={{flex:2,background:'#0f0',color:'#000',border:0,padding:'14px',borderRadius:10,fontWeight:'bold',fontSize:16}}>Call RealTime 🤙 Firebase</button></div></div></div>}
   {activePanel==='lang' && <div style={{margin:10,background:'#0a0a0a',border:'2px solid #0ff',borderRadius:12,padding:12}}><div style={{color:'#0ff',fontWeight:'bold'}}>🌐 NINO RealTime 10 Langs Firebase</div><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6,marginTop:8}}>{["en","yo","ig","ha","pcm","fr","es","zh","ar","pt"].map(l=><button key={l} onClick={()=>setLang(l)} style={{background:lang===l?'#0ff':'#111',color:lang===l?'#000':'#fff',border:'1px solid #222',padding:'8px',borderRadius:10,fontSize:10}}>{l.toUpperCase()}</button>)}</div><div style={{background:'#111',borderRadius:8,padding:12,marginTop:10,fontSize:12,minHeight:50,border:'2px solid #0ff'}}>{transText}</div><button onClick={translateReal} style={{width:'100%',marginTop:8,background:'#0ff',color:'#000',border:0,padding:'14px',borderRadius:10,fontWeight:'bold'}}>🎤 SPEAK EN → {lang.toUpperCase()} RealTime</button></div>}
   {activePanel==='pay' && <div style={{margin:10,background:'#0a0a0a',border:'2px solid #0ef',borderRadius:12,padding:12}}><div style={{color:'#0ef',fontWeight:'bold'}}>💳 GEA PAY RealTime - Paystack Flutterwave Monnify GPay + Firebase</div><div style={{display:'flex',gap:6,marginTop:8}}>{["Paystack","Flutterwave","Monnify","GPay"].map(m=><button key={m} onClick={()=>setPayMethod(m)} style={{background:payMethod===m?'#0ef':'#111',color:payMethod===m?'#000':'#fff',border:'1px solid #0ef',padding:'10px 14px',borderRadius:20,fontSize:11,fontWeight:'bold'}}>{m}</button>)}</div><div style={{marginTop:8}}>Total: ₦{cart.reduce((s,i)=>s+i.p,0)} | Balance: ₦{balance}</div><button onClick={payReal} style={{width:'100%',marginTop:8,background:'#0ef',color:'#000',border:0,padding:'12px',borderRadius:10,fontWeight:'bold'}}>Pay via {payMethod} Firebase RealTime</button></div>}
   <div style={{padding:10}}>
    {(posts.length?posts:[{id:'local1',u:"Apostle Dr Mighty",t:"Firebase Connecting... RealTime Posts will appear here!",l:0,comments:[],shares:0}]).map(p=><div key={p.id} style={{background:'#0a0a0a',border:'1px solid #222',borderRadius:12,padding:12,marginBottom:10}}>
     <div style={{display:'flex',gap:8}}><div style={{width:36,height:36,background:'#0f0',borderRadius:18}}/><div><div style={{fontSize:13,fontWeight:'bold'}}>{p.u}</div><div style={{fontSize:9,color:'#666'}}>Firebase RealTime</div></div></div>
     <div style={{marginTop:8,fontSize:14}}>{p.t}</div>
     <div style={{display:'flex',gap:8,marginTop:12}}><button onClick={()=>likeReal(p.id)} style={{background:'#111',border:'1px solid #222',color:'#888',borderRadius:20,padding:'8px 14px',fontSize:12,fontWeight:'bold'}}>❤️ {p.l||0} Love</button><button onClick={()=>setChatId(chatId===p.id?null:p.id)} style={{background:chatId===p.id?'#0f0':'#111',border:'1px solid #222',borderRadius:20,padding:'8px 14px',fontSize:12,fontWeight:'bold'}}>💬 Chat</button><button onClick={()=>shareReal('copy',p.id)} style={{background:'#0f0',color:'#000',borderRadius:20,padding:'8px 16px',fontSize:12,fontWeight:'bold'}}>🖇️ Share</button></div>
     {chatId===p.id && <div style={{marginTop:12,background:'#111',borderRadius:12,padding:12,border:'2px solid #0f0'}}><div style={{display:'flex',gap:8}}><input id={`c-${p.id}`} placeholder="Write chat - Firebase RealTime..." style={{flex:1,background:'#000',border:'2px solid #0f0',borderRadius:20,padding:'10px 14px',color:'#fff'}}/><button onClick={()=>chatReal(p.id)} style={{background:'#0f0',color:'#000',border:0,borderRadius:20,padding:'10px 18px',fontWeight:'bold'}}>Send Firebase</button></div><div style={{display:'flex',gap:6,marginTop:10}}><button onClick={()=>shareReal('wa',p.id)} style={{background:'#25D366',color:'#fff',border:0,padding:'8px 12px',borderRadius:10}}>WA</button><button onClick={()=>shareReal('fb',p.id)} style={{background:'#1877F2',color:'#fff',border:0,padding:'8px 12px',borderRadius:10}}>FB</button><button onClick={()=>shareReal('ig',p.id)} style={{background:'#d62976',color:'#fff',border:0,padding:'8px 12px',borderRadius:10}}>IG</button><button onClick={()=>shareReal('tt',p.id)} style={{background:'#000',color:'#fff',border:'1px solid #fff',padding:'8px 12px',borderRadius:10}}>TT</button><button onClick={()=>shareReal('yt',p.id)} style={{background:'#f00',color:'#fff',border:0,padding:'8px 12px',borderRadius:10}}>YT</button><button onClick={()=>shareReal('li',p.id)} style={{background:'#0A66C2',color:'#fff',border:0,padding:'8px 12px',borderRadius:10}}>in</button></div></div>}
    </div>)}
   </div>
  </div>
 </div>
)
}