name: UNZIP GEAPPLE 33
on: push
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract
        run: |
          unzip -o GEAPPLE_33.zip
          rm GEAPPLE_33.zip
          ls *.html
      - name: Push
        run: |
          git config user.name "Geapple"
          git config user.email "geapple@bot.com"
          git add .
          git commit -m "33 APPS EXTRACTED V3 96%" || true
          git push
